### ISSUE TITLE
doubts DWT_generateTrainData

### ISSUE THREAD

**Issue by profpedromoises** [tT0NG/WvSRx2#2]
first:

Why did you score 41 for height and width ???

STRIDE = 41
SIZE_INPUT = 41
SIZE_TARGET = SIZE_INPUT
PADDING = abs(int((SIZE_INPUT - SIZE_TARGET) / 2))

and why padding if you do not use it. because it always gets zero.

----------------------------------

second:

    for x in range(0, hei - SIZE_INPUT, STRIDE):
        for y in range(0, wid - SIZE_INPUT, STRIDE):
all images must have multiples height and width of 41 ?? to scan the entire image.

-------------------------

terceira

# APPEND EVERY 100 IMAGES TOGETHER TO SHUFFLE################################################

Why do you shuffle the pictures? this accelerates learning of the neural network

----------------------quarta

# APPEND 8 BATCHES TOGETHER TO FORM ONE H5 FILE################################################

You have 100 bathes of images because you unified only 8 batches

and enough to train the network ???

**Comment by tT0NG** [comment]
This is for generating the image dataset in h5 format. The code itself first generate smaller size h5 files then shuffle within the files. The small h5 files then are combined to generate the final h5 file for the training. 

The shuffle is to help with the SGD training procedure. There are 8 small h5 files to be combined to the final file. To understand the preparation for the training, please find tutorial at: https://cs230.stanford.edu/
