### ISSUE TITLE
doubts in wvsr

### ISSUE THREAD

**Issue by profpedromoises** [tT0NG/WvSRx2#3]
when you train the network you receive this format (64, 41,41,4)

but when you test an image the input is not in that format
for example ( see figure )
(1,288,360.4)

can help me at this point by explaining how the network trains
with this input

![image](https://user-images.githubusercontent.com/48567035/56235673-3beb9d00-605e-11e9-965e-448e9ad08fd0.png)

**Comment by tT0NG** [comment]
The CNN takes training patch for the training (B, W, H, C). During the test, the test input can have arbitrary size of W and H, where the B=1 and C=4. For the reason why the network would work with test image of arbitrary size, please refer to this tutorial: http://cs231n.github.io/convolutional-networks/
